export const imageMap: { [key: string]: any }= {
  "1": require("@/assets/pics/1.jpg"),
  "2": require("@/assets/pics/2.jpg"),
  "3": require("@/assets/pics/3.jpg"),
  "4": require("@/assets/pics/4.jpg"),
  "5": require("@/assets/pics/5.jpg"),
  "6": require("@/assets/pics/6.jpg"),
  "7": require("@/assets/pics/7.jpg"),
  "8": require("@/assets/pics/8.jpg"),
  "9": require("@/assets/pics/9.jpg"),
  "10": require("@/assets/pics/10.jpg"),
  "11": require("@/assets/pics/11.jpg"),
  "12": require("@/assets/pics/12.jpg"),
  "13": require("@/assets/pics/13.jpg"),
  "14": require("@/assets/pics/14.jpg"),
  "15": require("@/assets/pics/15.jpg"),
  "16": require("@/assets/pics/16.jpg"),
  "17": require("@/assets/pics/17.jpg"),
  "18": require("@/assets/pics/18.jpg"),
  "19": require("@/assets/pics/19.jpg"),
  "20": require("@/assets/pics/20.jpg"),
  "21": require("@/assets/pics/21.jpg"),
};
